# This tells Spring to ask Railway for the database address
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# This tells Spring to automatically build your tables in the new database
spring.jpa.hibernate.ddl-auto=update

# This tells Spring to use whatever "door" (port) Railway gives it
server.port=${PORT:8080}